//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesToPackage
    {
        public int id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> PackageId { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Service Service { get; set; }
    }
}
